### ISSUE TITLE
Turn off arrow collider once it hits an object

### ISSUE THREAD

**Issue by fznsakib** [fznsakib/Jacks-Room-VR#105]

**Comment by adamsadiq7** [comment]
![image](https://user-images.githubusercontent.com/43152210/54357291-abccc900-4655-11e9-961b-d68d225e477f.png)
Seems to be already done within the arrow code

**Comment by MichaelRol** [comment]
I’ll test it later today

**Comment by MichaelRol** [comment]
Just dropped a sick double kill on two army fools... which suggests the collider stayed on.
