### ISSUE TITLE
Cars end up on roof in wave 3, not allowing transition to wave 4

### ISSUE THREAD

**Issue by fznsakib** [fznsakib/Jacks-Room-VR#345]

**Comment by fznsakib** [comment]
Instead of fixing cars which may take some time, maybe just add a timer for around 10 seconds when enemiesToBeSpawned == 0, where at the end of it all enemies are destroyed

**Comment by adamsadiq7** [comment]
Is there a collider on the roof?

**Comment by fznsakib** [comment]
> Is there a collider on the roof?

Yeah there is
