### ISSUE TITLE
Make the sound effects for punching play only when it qualifies as a punch

### ISSUE THREAD

**Issue by fznsakib** [fznsakib/Jacks-Room-VR#377]
At the moment it plays whenever there is a collision. This means if your punch is quite slow it'll play the sound effect multiple times in a row which sounds bad. To fix, play the sound effect only where there animator and agent is stopped/health is reduced

**Comment by MarkErgusNicholl** [comment]
Resolved in #390 , tolerance to what is considered a successful punch can be manipulated in soldierScript, carScript and BoyCollisionDetector.
